[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Manejo de SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200